/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.clightning4j.template

import io.github.clightning4j.template.plugin.Plugin

fun main(args: Array<String>) {
    val plugin = Plugin()
    plugin.start()
}
