name: Building
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Inti JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check Kotling format
        run: |
          ./gradlew lintKotlin
      - name: Build with Gradle
        run: |
          ./gradlew createRunnableScript