/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.clightning4j.template

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {
    @Test fun testAppHasAGreeting() {
        assertTrue { true }
    }
}
